Lista para o Teste 3 - Gradiente Descendente,
Otimização e Redução de Dimensão

In [39]:
using LinearAlgebra

function desc_grad(lr,vec,grad)
    return vec + lr*grad
end

function grad(M,c,v)
    return M*v + c
end


#questão 1:

function funcao(v)
    x=v[1]
    y=v[2]
    return (2x+3y-5)^2 + (3x+4y-7)^2
end
M = [26 36;
    36 50]
c = -[62 ; 86]
v = [2;4]
print("começo : ",funcao(v))
lr = -0.01
for i in 1:1000
    v_grad = grad(M,c,v) 
    v = desc_grad(lr,v,v_grad)
end

print("\n",funcao(v))
grad(M,c,[0;0])*lr

começo : 346
0.008162979057531456

2-element Vector{Float64}:
 0.62
 0.86

In [40]:
#questao 2 
function f(ponto)
    x = ponto[1]
    y=ponto[2]
    return (y-1)^4 + x^2*y^2+1
end
p = [1;1]
lr = 0.1
for i in 1:2
    x,y=p
    vg = [ 2*x*y^2 ; 4*(y-1)^3 + 2*x^2*y]

    p = p-lr*vg
    print('\n',p)
end


[0.8, 0.8]
[0.6976, 0.7008]

In [41]:
#questao 3
#Ponto inicial e learning rate
function f3(p)
    x=p[1]
    y=p[2]
    return 3*x*x + 4*x*x + 4*x*y + 6*x + 10*y + 7
end
p = [121;-21]
lr = 0.27
print(f3(p),'\n')

M = [6 4 ; 4 8]
c = [6 ;10]
for i in 1:50
    x,y=p
    #colocar funcao do vetor gradiente abaixo
    x = x*(1-6*lr) - 4*lr*y - 6*lr
    y = y*(1-8*lr) - 4*lr*x -10*lr
    
    p = [x,y]
end
print(p,' ',f3(p))

92846
[-0.28198200634769055, -1.1116870470844424] -3.9982625697330434

In [42]:
#questao 4

function f4(x)
    return ((x-3)^2)/2
end

xi = randn()
lr = 1.9
for i in 1:1000
    # print('\n',xi)
    xi = xi*(1-lr) + 3*lr
    # print(xi,' ')
end
    print('\n',xi,' ',f4(xi))


2.9999999999999982 1.5777218104420236e-30

In [43]:
#questao 9
import Plots

xi = [i for i in -10:10]
yi = [0 for i in -10:10]
for i in 1:21
    if(xi[i]==0)
        yi[i]=1
    end
end
 function vandermonde(x_values,grau)
        l = size(x_values)[1]
        c = grau+1
        vandermonde = zeros(l,c)
    
        for i in 1:l  #para cada linha
            for j in 1:c
                vandermonde[i,j] = x_values[i]^(j-1)
            end
        end
        return vandermonde
    end

Vand = vandermonde(xi,1)

coef = Vand\yi
coef[1]- 1/21

6.938893903907228e-18

In [106]:
M = rand(Int8,4,4)

4×4 Matrix{Int8}:
   2    63   93    44
  23  -111  -34   103
 -85    17   78    30
 -40    29   76  -121

In [125]:
function erro(M,A)
    return norm(M-A)
end
function dec_QR(A)
    m,n = size(A)
    R = zeros(m,n)
    Q = zeros(m,n)

    for i in 1:n
        vetor = A[:,i]
    
        for j in 1:(i-1)
            u = Q[:,j] #pega vetor já ortogonalizado 'u'
            prod_interno = (vetor')*u #ve de quantos 'u' o 'vetor' é composto
            R[j,i] = prod_interno #adiciona na matriz R
            vetor-=(prod_interno * u) #cria o ortogonal a u
        end
        norma = norm(vetor)
        R[i,i] = norma
        Q[:,i] = vetor/norma
    end

    return Q,R
end


function als(M,rank)
    n,m = size(M)
    # L =  [3 ; 1 ; 2]
    L = randn(n,rank)
    R = 1
    for i in 1:60
        R = (L\M)
        L = (R' \ M')'
        # print("r=",R)
    end
    return L,R
end


function mysvd(M,r)
    B,C = als(M,r)
    C = C'
    Qb,Rb = dec_QR(B)
    Qc,Rc = dec_QR(C)
    display(Rb*Rc')
end

# B,C = als(M,3)
# display(B*C)
# print(erro(B*C,M))

mysvd(M,3)

4×4 Matrix{Float64}:
 83.8678   -56.833   -25.6458  0.0
 16.8838   169.509   105.179   0.0
 -5.82395  -41.3616  146.485   0.0
  0.0        0.0       0.0     0.0

In [45]:
#questao 12

UxF = [ 0.82 0.18 0.5 0.1 0.26 ;
        0.74 0.26 0.5 0.2 0.32 ;
       0.34 0.69 0.5 0.7 0.62 ;
        0.58 0.42 0.5 0.4 0.44 ;
        0.1 0.9 0.5 1 0.8]
B,C = als(UxF,2)


l,c = size(C)
best = C[:,2]
for i in 2:c
    filme = C[:,i] 
    if( norm(C[:,1]-filme)< norm(C[:,1]-best)) 
        best = filme
    end
end

print("Filmes como vetores em 2d:\n")
display(C)

print("recomendacao:")
display(best)
#recomendação seria o hobbit


Filmes como vetores em 2d:


2×5 Matrix{Float64}:
  0.27757  -0.32175   -0.0196781  -0.391239  -0.242614
 -0.59609   0.437481  -0.0827363   0.558955   0.302279

recomendacao:

2-element Vector{Float64}:
 -0.01967811134615167
 -0.08273633087611468

In [46]:
#checando questao 13
b = [1;1]
A = [2 3 ; 1 0]

c = b\A
b = (c'\A')'
c = b\A
b= (c'\A')'
b*c

2×2 Matrix{Float64}:
 2.13006   2.90462
 0.349711  0.476879

In [47]:
#questao 14
erro_minimo = 35^7

c= 0
while(true)
    c+=1
    A = rand(Int8,4,6)
    B,C = als(A,2)
    erro = norm( A - B*C )
    if(erro<erro_minimo)
        erro_minimo=erro
        print(erro_minimo," na tentativa ",c,"\n")
    end

    if(erro<10)
        break
    end
    flush(stdout)
end

# print("encontrado apos tentativa ",c)
# display(A)


160.80307185517594 na tentativa 1
146.41741996416744 na tentativa 2
105.74509024677386 na tentativa 5
87.25022896364307 na tentativa 19
80.19613857508554 na tentativa 39
77.52889674006423 na tentativa 40
73.09442912879744 na tentativa 60
69.62962870971741 na tentativa 289
48.90843092617012 na tentativa 347


LoadError: InterruptException: