In [36]:
l = [ 1 0 0
    2 1 0
    3 4 5]
u=[ 2 1 1
    0 3 2
    0 0 1]
A = l*u
e1 = [ 1,0,0]
y = l\e1
display(y)
x = u\y

3-element Vector{Float64}:
  1.0
 -2.0
  1.0

3-element Vector{Float64}:
  0.6666666666666666
 -1.3333333333333333
  1.0

In [1]:
[i for i in rand(-2:3)]

0-dimensional Array{Int64, 0}:
0

In [42]:
1 +4/3 -1

1.333333333333333

In [1]:
[(rand(-10:10) for i in 1:10)]

1-element Vector{Base.Generator{UnitRange{Int64}, var"#3#4"}}:
 Base.Generator{UnitRange{Int64}, var"#3#4"}(var"#3#4"(), 1:10)

In [50]:
using LinearAlgebra

A = [0 1
    1 1]

function nao_fechada(n)

    A = [0 1
    1 1]
    inicio = [0;1]
    for i in 1:(n-1)
        inicio = A*inicio
    end
    
    return inicio[1]
end

# for i in 1:13
#     display(nao_fechada(i))
# end

function fechada(n)
    
    A = [ 0 1 ; 1 1]
    avl,avt = eigen(A)
    c = avt\([ 0 ; 1])
    resultado = c[1]*(avl[1]^n)*avt[:,1] + c[2]*(avl[2]^n)*avt[:,2]
    
    return resultado[1]
    
end

@time begin
for i in 1:100000
    # nao_fechada(i)
    fechada(i)
end
end
display(nao_fechada(30))

  0.453376 seconds (2.50 M allocations: 221.252 MiB, 12.86% gc time)


514229

In [60]:
A = [-4 18 18
    14 -37 -40
    -14 42 45]
I3 = Matrix(I,3,3)
eigen(A)

eigen(inv(A - 2*I3))

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.1666666666666653
  0.33333333333333337
  0.9999999999999948
vectors:
3×3 Matrix{Float64}:
 -0.333333   0.212      0.0
  0.666667  -0.635999  -0.707107
 -0.666667   0.741999   0.707107

In [78]:
#exercicio 33
V = zeros(3,3)
x = [30,45,60]
y = [sqrt(3)/2 ; sqrt(2)/2 ; 1/2]
for i in 1:3
    V[i,:] = [ 1; x[i]^1 ;x[i]^2 ]
end
c = V\y
aprx = [ 1; 40 ; 40^2]
aprx' *  c

0.7654338952290286

In [95]:
#exercicio 34

A = [ 1 log(2);
    1 log(4);
    1 log(6)]
b = [log(1);log(4);log(11)]
cs = A\b
c1 = exp(cs[1])
c2 = cs[2]

c1*(5^c2)+3

10.039037288588474

In [98]:
#exercicio 35
V = zeros(3,3)
x = [1,2,4]
y = [0;1;2]
for i in 1:3
    V[i,:] = [ 1; x[i]^1 ;x[i]^2 ]
end
c  = V\y

3-element Vector{Float64}:
 -1.3333333333333333
  1.5
 -0.16666666666666669