In [16]:
b = 0.001
p = 0.9
s = 1 - b - p

0.09899999999999998

In [45]:
function PIi(i)
    return (b*(p^i))/((b+p)^(i+1))
end


lista = [PIi(x) for x in 1:7146]


7146-element Vector{Float64}:
 0.0011086460844468042
 0.0011074156226438664
 0.0011061865265033072
 0.001104958794509408
 0.001103732425148132
 0.001102507416907124
 0.001101283768275707
 0.0011000614777448793
 0.0010988405438073154
 0.001097620964957363
 0.0010964027396910395
 0.0010951858665060328
 0.0010939703439016976
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [57]:
tabuleiro = zeros(Int,8,8)
c=1
for i in 1:8
    for j in 1:8
        tabuleiro[i,j]=c
        c+=1
    end
end

tabuleiro

8×8 Matrix{Int64}:
  1   2   3   4   5   6   7   8
  9  10  11  12  13  14  15  16
 17  18  19  20  21  22  23  24
 25  26  27  28  29  30  31  32
 33  34  35  36  37  38  39  40
 41  42  43  44  45  46  47  48
 49  50  51  52  53  54  55  56
 57  58  59  60  61  62  63  64

In [116]:
tm = zeros(64,64)

p = 1/14

for i in 1:64
    #pegar linha do tabuleiro na qual está a posicao i
    linha = tabuleiro[Int(ceil(i/8)),:]
    c = i%8
    if c==0
        c = 8
    end
    col = tabuleiro[:,c]

    #preenchendo linha
    for j in 1:64
        if ( (j in linha) || (j in col)) && j!=i
            tm[i,j] = p
        end
    end
    
end
tm

64×64 Matrix{Float64}:
 0.0        0.0714286  0.0714286  …  0.0        0.0        0.0
 0.0714286  0.0        0.0714286     0.0        0.0        0.0
 0.0714286  0.0714286  0.0           0.0        0.0        0.0
 0.0714286  0.0714286  0.0714286     0.0        0.0        0.0
 0.0714286  0.0714286  0.0714286     0.0        0.0        0.0
 0.0714286  0.0714286  0.0714286  …  0.0714286  0.0        0.0
 0.0714286  0.0714286  0.0714286     0.0        0.0714286  0.0
 0.0714286  0.0714286  0.0714286     0.0        0.0        0.0714286
 0.0714286  0.0        0.0           0.0        0.0        0.0
 0.0        0.0714286  0.0           0.0        0.0        0.0
 0.0        0.0        0.0714286  …  0.0        0.0        0.0
 0.0        0.0        0.0           0.0        0.0        0.0
 0.0        0.0        0.0           0.0        0.0        0.0
 ⋮                                ⋱                        
 0.0        0.0        0.0           0.0        0.0        0.0
 0.0        0.0        0.0   

In [31]:
tm = [6/7 1/7 0;
    1/2 3/7 1/14;
    0 0 1]

tm^99

3×3 Matrix{Float64}:
 0.189816  0.0486969  0.761487
 0.170439  0.0437257  0.785835
 0.0       0.0        1.0

In [1]:
x = Set(vcat([1,23],[1,2]))
rand(x)

23

In [27]:
#naval battle = nb
nb = [
    1/12 1/6 1/12 1/6 1/3 1/6 0 0 0;
    0 1/12 1/4 0 1/6 1/2 0 0 0;
    0 0 1 0 0 0 0 0 0;
    0 0 0 1/6 1/6 0 1/3 1/3 0;
    0 0 0 0 1/6 1/6 0 1/3 1/3;
    0 0 0 0 0 1 0 0 0;
    0 0 0 0 0 0 1 0 0;
    0 0 0 0 0 0 0 1 0;
    0 0 0 0 0 0 0 0 1;]


st = nb^99999;

#probabilidade de destroieres ganharem 
p = 0 
for i in 1:9
    if (i in [3,6])
      p+= sum( st[1,i] )          
    end
end
print("Probabilidade de destroieres ganharem: ", p)


#probabilidade de encouraçados ganharem 
p = 0 
for i in 1:9
    if (i in [7,8])
      p+= sum( st[1,i] )          
    end
end
print("\nProbabilidade de encouraçados ganharem: ", p)

Probabilidade de destroieres ganharem: 0.5080991735537189
Probabilidade de encouraçados ganharem: 0.3186776859504132

In [176]:
function sample_point()
    p = rand(2)
    for i in 1:2
        if(rand() >= 0.5)
            p[i] *= -1
        end
    end
    return p
end

function estimate_pi(epsilon,delta)
    n = (12 * log(2/delta) / (pi * epsilon^2) ) + 1
    print(n)
    inside = 0;
    for i in 1:n
        p = sample_point()
        if ((p' * p) <=1)
            inside+=1
        end
    end
    return 4 * (inside/n)
end


ep = estimate_pi(0.01,0.01)

display( (ep-pi)/pi)

202381.81574938082

-0.001052570444180919

In [2]:
function setbit(x,n)
    x |= 2^(n-1)
    return x
end

function checkbit(N,n)
    return (N >> (n-1)) & 1 != 0
end

function dnf_exp(v)
    return (v[1] && v[3]) || (!(v[1]) && v[2]) || (v[2]&& !(v[3]))    
end

function dnf_test(exp,n)
    acc = 0
    for i in 0:(2^n - 1)
        #create array of booleans
        values = [checkbit(i,j) for j in 1:3]
        display(values)
        if(exp(values))
            acc+=1
        end
    end
    print("Numero de atribuicoes que satisfazem = ",acc,'\n')
end

dnf_test(dnf_exp,3)


3-element Vector{Bool}:
 0
 0
 0

3-element Vector{Bool}:
 1
 0
 0

3-element Vector{Bool}:
 0
 1
 0

3-element Vector{Bool}:
 1
 1
 0

3-element Vector{Bool}:
 0
 0
 1

3-element Vector{Bool}:
 1
 0
 1

3-element Vector{Bool}:
 0
 1
 1

3-element Vector{Bool}:
 1
 1
 1

Numero de atribuicoes que satisfazem = 5


In [4]:
P = [0 1/3 0 1/3 1/3;
    1/3 1/3 1/3 0 0;
    0 1/3 1/3 0 1/3;
    1/3 0 1/3 0 1/3;
    1/3 0 0 2/3 0]

P^1000

5×5 Matrix{Float64}:
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2