In [15]:
using LinearAlgebra
A = Symmetric(randn(3,3))

3×3 Symmetric{Float64, Matrix{Float64}}:
 -0.364648   -0.155185    -0.0871901
 -0.155185   -0.00769301  -0.0796511
 -0.0871901  -0.0796511    0.222444

In [16]:
# Retorna autovalor e autovetor dominante
function mp(A)
    m,n = size(A)
    if(m!=n)
        print("Dimensoes erradas! Matriz não quadradada")
        return
    end
    v = ones(m)
    for i in 1:60
        v = A*v
        v = (1/norm(v))*v
    end
    autovalor = (v' * (A*v) )/ (v' * v)
    return v,autovalor
end
display(eigen(A))
avt1, avl1 = mp(A)
# B = A - autovalor*autovetor*autovetor'
# eigen(B)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.4408854090861307
  0.04097401473795445
  0.25001447503177726
vectors:
3×3 Matrix{Float64}:
 -0.918733   0.388152  -0.0725789
 -0.359258  -0.897905  -0.254362
 -0.1639    -0.207616   0.964382

([0.9187329270342712, 0.3592583545917469, 0.16390010201055785], -0.4408854090861315)

In [18]:
B = A - avl1*(avt1*avt1')
display(eigen(B))
display(mp(B))

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 6.3301091289926934e-18
 0.04097401473795423
 0.25001447503177676
vectors:
3×3 Matrix{Float64}:
 0.918733   0.388152  -0.0725789
 0.359258  -0.897905  -0.254362
 0.1639    -0.207616   0.964382

([-0.07257892073578862, -0.2543618980508834, 0.9643818357293859], 0.25001447503177726)

-2.0182929021815337